### PR TITLE
Add Ivy faces

### PR DESCRIPTION
**Pull request by manuel-uberti**
Basic support for ivy/swiper/counsel.

### CODE REVIEW

**Comment by wasamasa** [comment]
Sorry for getting to this so late.  Things to be improved:
- Please insert the block at the right position by alphabetical sorting and with the name of the file containing the faces on top of it for consistency's sake
- Cover all `defface`s in ivy.el, currently `ivy-subdir`, `ivy-modified-buffer` and `ivy-virtual` are missing
- `ivy-minibuffer-match-face-1` makes it essentially invisible if I enter space-separated terms in an ivy prompt, better change it to orange like the rest?

**Comment by manuel-uberti** [comment]
Thanks for the feedback. I'll fix it and push another commit.

**Comment by manuel-uberti** [comment]
I pushed the changes. Do you need me to squash the commits into a single one?

**Comment by wasamasa** [comment]
Yup, that would have been the next thing I'd have asked for.

**Comment by manuel-uberti** [comment]
Done :)

**Comment by wasamasa** [comment]
Oh and the block still precedes `faces.el` which is wrong, it should be put after `info.el`.

**Comment by manuel-uberti** [comment]
Oh, you're right, ido and isearch blocks are right before `faces.el` too, that's why I put it there. Do you want me to sort them too?

**Comment by wasamasa** [comment]
My bad, I'll do that after this one is merged.

**Comment by manuel-uberti** [comment]
Great. Thanks for the help.

**Comment by wasamasa** [comment]
Thanks, I've fixed this now.

**Pull request merged**
